// @ts-check
// `@type` JSDoc annotations allow editor autocompletion and type checking
// (when paired with `@ts-check`).
// There are various equivalent ways to declare your Docusaurus config.
// See: https://docusaurus.io/docs/api/docusaurus-config

import {themes as prismThemes} from 'prism-react-renderer';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// This is the whole site: homepage (src/pages/index.js) plus three
// independent documentation sections (varistar, env-maker, ogle), each its
// own plugin-content-docs instance. The navbar deliberately carries no
// cross-project links — each project's own autogenerated sidebar is its
// only in-docs navigation, so browsing /varistar never surfaces env-maker
// or ogle. See README.md.

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'Projects Documentation',
  tagline: 'jj-sm public projects documentation',
  favicon: 'img/favicon.ico',

  // Future flags, see https://docusaurus.io/docs/api/docusaurus-config#future
  future: {
    v4: true, // Improve compatibility with the upcoming Docusaurus v4
  },

  url: 'https://docs.jjsm.science',
  baseUrl: '/',

  organizationName: 'jj-sm',
  projectName: 'docs',

  onBrokenLinks: 'throw',

  // `favicon` above only emits one <link rel="icon">. The rest of the
  // generated favicon package (static/img/favicon-*.png, apple-touch-icon,
  // android-chrome icons, site.webmanifest) is wired in here so browsers/
  // devices that don't use the SVG favicon still get the same icon.
  headTags: [
    {
      tagName: 'link',
      attributes: {
        rel: 'icon',
        type: 'image/png',
        sizes: '32x32',
        href: '/img/favicon-32x32.png',
      },
    },
    {
      tagName: 'link',
      attributes: {
        rel: 'icon',
        type: 'image/png',
        sizes: '16x16',
        href: '/img/favicon-16x16.png',
      },
    },
    {
      tagName: 'link',
      attributes: {
        rel: 'apple-touch-icon',
        sizes: '180x180',
        href: '/img/apple-touch-icon.png',
      },
    },
    {
      tagName: 'link',
      attributes: {
        rel: 'manifest',
        href: '/img/site.webmanifest',
      },
    },
  ],

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        // The default single "docs" instance is replaced by the three
        // multi-instance plugin-content-docs entries below.
        docs: false,
        blog: false,
        pages: {}, // src/pages/index.js is the homepage
        theme: {
          customCss: './src/css/custom.css',
        },
      }),
    ],
  ],

  plugins: [
    [
      '@docusaurus/plugin-content-docs',
      /** @type {import('@docusaurus/plugin-content-docs').Options} */
      ({
        id: 'varistar',
        path: 'varistar/docs',
        routeBasePath: 'varistar',
        sidebarPath: './varistar/sidebars.js',
      }),
    ],
    [
      '@docusaurus/plugin-content-docs',
      /** @type {import('@docusaurus/plugin-content-docs').Options} */
      ({
        id: 'env-maker',
        path: 'env-maker/docs',
        routeBasePath: 'env-maker',
        sidebarPath: './env-maker/sidebars.js',
      }),
    ],
    [
      '@docusaurus/plugin-content-docs',
      /** @type {import('@docusaurus/plugin-content-docs').Options} */
      ({
        id: 'ogle',
        path: 'ogle/docs',
        routeBasePath: 'ogle',
        sidebarPath: './ogle/sidebars.js',
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      colorMode: {
        respectPrefersColorScheme: true,
      },
      // navbar.title/items and footer.links are intentionally NOT set here:
      // src/theme/Navbar/Content and src/theme/Footer render per-project
      // content instead (name + GitHub link, from src/data/docsProjects.js),
      // since this global themeConfig can't vary by route. logo/colorMode
      // stay here since the toggle and Logo components still read them.
      navbar: {
        logo: {
          alt: 'Logo',
          src: 'img/logo.png',
          width: 32,
          height: 32,
        },
      },
      footer: {
        style: 'light',
        logo: {
          alt: 'Logo',
          src: 'img/logo.png',
          href: '/',
          width: 32,
          height: 32,
        },
        copyright: `Copyright © ${new Date().getFullYear()} Juan José Sánchez Medina. All rights reserved.`,
      },
      prism: {
        theme: prismThemes.github,
        darkTheme: prismThemes.dracula,
      },
    }),
};

export default config;
